# Logits

In [1]:
import numpy as np

# Raw scores = logits
logits = np.array([5.2, 2.1, 1.0])

print("Logits:")
print(logits)

Logits:
[5.2 2.1 1. ]


# Softmax

In [2]:
def softmax(x):
    exp_x = np.exp(x - np.max(x))
    return exp_x / np.sum(exp_x)

probabilities = softmax(logits)

print("Probabilities:")
print(probabilities)

print("Sum:", np.sum(probabilities))

Probabilities:
[0.94335637 0.04249745 0.01414617]
Sum: 1.0


# Temperature

In [3]:
def softmax_temperature(logits, temperature=1.0):
    scaled_logits = logits / temperature
    return softmax(scaled_logits)

print("Temperature = 0.5")
print(softmax_temperature(logits, 0.5))

print("\nTemperature = 1.0")
print(softmax_temperature(logits, 1.0))

print("\nTemperature = 2.0")
print(softmax_temperature(logits, 2.0))

Temperature = 0.5
[9.97750772e-01 2.02486599e-03 2.24361546e-04]

Temperature = 1.0
[0.94335637 0.04249745 0.01414617]

Temperature = 2.0
[0.74922957 0.15902246 0.09174798]


# Top-k Sampling

In [4]:
import numpy as np

# Raw scores (logits)
logits = np.array([5.0, 4.0, 3.0, 2.0, 1.0])

k = 2

# Top-k indices
top_k_indices = np.argsort(logits)[-k:][::-1]

print("Top-k indices:", top_k_indices)
print("Top-k logits:", logits[top_k_indices])

Top-k indices: [0 1]
Top-k logits: [5. 4.]


In [5]:
top_k_logits = logits[top_k_indices]

top_k_probs = np.exp(top_k_logits - np.max(top_k_logits))
top_k_probs = top_k_probs / np.sum(top_k_probs)

print("Top-k probabilities:")
print(top_k_probs)

Top-k probabilities:
[0.73105858 0.26894142]


# Hugging Face — Real LLM Generation

In [7]:
from transformers import pipeline

In [8]:
generator = pipeline(
    "text-generation",
    model="distilbert/distilgpt2"
)

config.json:   0%|          | 0.00/762 [00:00<?, ?B/s]

C:\Users\Dell\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:130: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Dell\.cache\huggingface\hub\models--distilbert--distilgpt2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


model.safetensors:   0%|          | 0.00/353M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/76 [00:00<?, ?it/s]

GPT2LMHeadModel LOAD REPORT from: distilbert/distilgpt2
Key                                        | Status     |  | 
-------------------------------------------+------------+--+-
transformer.h.{0, 1, 2, 3, 4, 5}.attn.bias | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [9]:
result = generator(
    "The future of AI is",
    max_new_tokens=40,
    do_sample=True,
    temperature=0.7
)

print(result[0]["generated_text"])

Passing `generation_config` together with generation-related arguments=({'max_new_tokens', 'do_sample', 'temperature'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Both `max_new_tokens` (=40) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


The future of AI is a lot like the present, but it’s only going to get more interesting.‡


In [ ]:
!pip install -U transformers torch

# BERT Demo

In [ ]:
from transformers import pipeline

classifier = pipeline(
    "sentiment-analysis",
    model="distilbert-base-uncased-finetuned-sst-2-english"
)

result = classifier(
    "I really enjoyed this movie"
)

print(result)

# T5 Demo

In [ ]:
from transformers import pipeline

translator = pipeline(
    "translation_en_to_fr",
    model="t5-small"
)

result = translator(
    "I love artificial intelligence"
)

print(result)

AI
↓
NLP
↓
Tokenization
↓
BOW / TF-IDF
↓
Word2Vec
↓
Embeddings
↓
Transformer
↓
Attention
↓
Q / K / V
↓
Multi-Head Attention
↓
Positional Encoding
↓
BERT
↓
GPT
↓
T5
↓
LLM GENERATION
    ├── Pretraining
    ├── Next-token prediction
    ├── Logits
    ├── Softmax
    ├── Inference
    ├── Temperature
    ├── Top-k
    ├── Top-p
    └── Context Window