In [1]:
!pip install numpy pandas matplotlib scikit-learn gensim sentence-transformers faiss-cpu transformers torch accelerate

   ---------------------------------------- 0.0/740.6 kB ? eta -:--:--
   ---------------------------------------- 0.0/740.6 kB ? eta -:--:--
   ---------------------------------------- 0.0/740.6 kB ? eta -:--:--
   ---------------------------- ----------- 524.3/740.6 kB 1.9 MB/s eta 0:00:01
   ---------------------------------------- 740.6/740.6 kB 1.2 MB/s eta 0:00:00
   ---------------------------------------- 0.0/16.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.3 MB ? eta -:--:--
    --------------------------------------- 0.3/16.3 MB ? eta -:--:--
    --------------------------------------- 0.3/16.3 MB ? eta -:--:--
   - -------------------------------------- 0.5/16.3 MB 781.3 kB/s eta 0:00:21
   - -------------------------------------- 0.8/16.3 MB 943.1 kB/s eta 0:00:17
   -- ------------------------------------- 1.0/16.3 MB 940.5 kB/s eta 0:00:17
   --- ------------------------------------ 1.3/16.3 MB 1.0 MB/s eta 0:00:15
   --- --------------------------

# 1. Tokenization

In [2]:
text = "I love Generative AI"

tokens = text.split()

print("Text:", text)
print("Tokens:", tokens)
print("Number of tokens:", len(tokens))

Text: I love Generative AI
Tokens: ['I', 'love', 'Generative', 'AI']
Number of tokens: 4


# Hugging Face tokenizer

In [4]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

text = "I love Generative AI"

tokens = tokenizer.tokenize(text)
token_ids = tokenizer.encode(text)

print("Tokens:", tokens)
print("Token IDs:", token_ids)

Tokens: ['i', 'love', 'genera', '##tive', 'ai']
Token IDs: [101, 1045, 2293, 11416, 6024, 9932, 102]


# 2. Bag of Words

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

documents = [
    "I love machine learning",
    "I love artificial intelligence",
    "Machine learning is powerful"
]

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(documents)

print("Vocabulary:")
print(vectorizer.get_feature_names_out())

print("\nMatrix:")
print(X.toarray())

Vocabulary:
['artificial' 'intelligence' 'is' 'learning' 'love' 'machine' 'powerful']

Matrix:
[[0 0 0 1 1 1 0]
 [1 1 0 0 1 0 0]
 [0 0 1 1 0 1 1]]


# TF-IDF

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer

documents = [
    "I love machine learning",
    "I love artificial intelligence",
    "Machine learning is powerful"
]

tfidf = TfidfVectorizer()

X = tfidf.fit_transform(documents)

print("Words:")
print(tfidf.get_feature_names_out())

print("\nTF-IDF Matrix:")
print(X.toarray())

Words:
['artificial' 'intelligence' 'is' 'learning' 'love' 'machine' 'powerful']

TF-IDF Matrix:
[[0.         0.         0.         0.57735027 0.57735027 0.57735027
  0.        ]
 [0.62276601 0.62276601 0.         0.         0.4736296  0.
  0.        ]
 [0.         0.         0.5628291  0.42804604 0.         0.42804604
  0.5628291 ]]


# Word2Vec

In [7]:
from gensim.models import Word2Vec

sentences = [
    ["i", "love", "machine", "learning"],
    ["machine", "learning", "is", "powerful"],
    ["i", "love", "artificial", "intelligence"],
    ["artificial", "intelligence", "is", "useful"]
]

model = Word2Vec(
    sentences,
    vector_size=50,
    window=2,
    min_count=1,
    workers=1
)

print(model.wv["machine"])

[ 0.00018913  0.00615464 -0.01362529 -0.00275093  0.01533716  0.01469282
 -0.00734659  0.0052854  -0.01663426  0.01241097 -0.00927464 -0.00632821
  0.01862271  0.00174677  0.01498141 -0.01214813  0.01032101  0.01984565
 -0.01691478 -0.01027138 -0.01412967 -0.0097253  -0.00755713 -0.0170724
  0.01591121 -0.00968788  0.01684723  0.01052514 -0.01310005  0.00791574
  0.0109403  -0.01485307 -0.01481144 -0.00495046 -0.01725145 -0.00316314
 -0.00080687  0.00659937  0.00288376 -0.00176284 -0.01118812  0.00346073
 -0.00179474  0.01358738  0.00794718  0.00905894  0.00286861 -0.00539971
 -0.00873363 -0.00206415]
