# Logits

In [1]:
import numpy as np

# Raw scores = logits
logits = np.array([5.2, 2.1, 1.0])

print("Logits:")
print(logits)

Logits:
[5.2 2.1 1. ]


# Softmax

In [2]:
def softmax(x):
    exp_x = np.exp(x - np.max(x))
    return exp_x / np.sum(exp_x)

probabilities = softmax(logits)

print("Probabilities:")
print(probabilities)

print("Sum:", np.sum(probabilities))

Probabilities:
[0.94335637 0.04249745 0.01414617]
Sum: 1.0


# Temperature

In [3]:
def softmax_temperature(logits, temperature=1.0):
    scaled_logits = logits / temperature
    return softmax(scaled_logits)

print("Temperature = 0.5")
print(softmax_temperature(logits, 0.5))

print("\nTemperature = 1.0")
print(softmax_temperature(logits, 1.0))

print("\nTemperature = 2.0")
print(softmax_temperature(logits, 2.0))

Temperature = 0.5
[9.97750772e-01 2.02486599e-03 2.24361546e-04]

Temperature = 1.0
[0.94335637 0.04249745 0.01414617]

Temperature = 2.0
[0.74922957 0.15902246 0.09174798]


# Top-k Sampling

In [4]:
import numpy as np

# Raw scores (logits)
logits = np.array([5.0, 4.0, 3.0, 2.0, 1.0])

k = 2

# Top-k indices
top_k_indices = np.argsort(logits)[-k:][::-1]

print("Top-k indices:", top_k_indices)
print("Top-k logits:", logits[top_k_indices])

Top-k indices: [0 1]
Top-k logits: [5. 4.]


In [5]:
top_k_logits = logits[top_k_indices]

top_k_probs = np.exp(top_k_logits - np.max(top_k_logits))
top_k_probs = top_k_probs / np.sum(top_k_probs)

print("Top-k probabilities:")
print(top_k_probs)

Top-k probabilities:
[0.73105858 0.26894142]


# Hugging Face — Real LLM Generation

In [6]:
from transformers import pipeline

In [7]:
generator = pipeline(
    "text-generation",
    model="distilbert/distilgpt2"
)

Loading weights:   0%|          | 0/76 [00:00<?, ?it/s]

In [8]:
result = generator(
    "The future of AI is",
    max_new_tokens=40,
    do_sample=True,
    temperature=0.7
)

print(result[0]["generated_text"])

[transformers] Passing `generation_config` together with generation-related arguments=({'do_sample', 'max_new_tokens', 'temperature'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
[transformers] Both `max_new_tokens` (=40) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer GPT2Tokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.


The future of AI is not in our favour, but for the future of AI.






We hope you enjoyed this article and want to keep up to date with all the latest developments and insights.


In [9]:
!pip install -U transformers torch

In [10]:
!pip uninstall -y transformers huggingface_hub

Found existing installation: transformers 5.17.0
Uninstalling transformers-5.17.0:
  Successfully uninstalled transformers-5.17.0
Found existing installation: huggingface_hub 1.33.0
Uninstalling huggingface_hub-1.33.0:
  Successfully uninstalled huggingface_hub-1.33.0


In [ ]:
!pip install transformers huggingface_hub torch

# BERT Demo

In [ ]:
import transformers
import huggingface_hub

print("Transformers:", transformers.__version__)
print("Hugging Face Hub:", huggingface_hub.__version__)

In [ ]:
from transformers import pipeline

classifier = pipeline("sentiment-analysis")

result = classifier("I really enjoyed this movie")

print(result)

# T5 Demo

In [ ]:
from transformers import pipeline

translator = pipeline(
    "translation_en_to_fr",
    model="t5-small"
)

result = translator(
    "I love artificial intelligence"
)

print(result)

AI
↓
NLP
↓
Tokenization
↓
BOW / TF-IDF
↓
Word2Vec
↓
Embeddings
↓
Transformer
↓
Attention
↓
Q / K / V
↓
Multi-Head Attention
↓
Positional Encoding
↓
BERT
↓
GPT
↓
T5
↓
LLM GENERATION
    ├── Pretraining
    ├── Next-token prediction
    ├── Logits
    ├── Softmax
    ├── Inference
    ├── Temperature
    ├── Top-k
    ├── Top-p
    └── Context Window